# Generated by Django 3.2.1 on 2021-05-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerturnover',
            name='point_length',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='passengerturnover',
            name='point_turnover',
            field=models.FloatField(),
        ),
    ]
